# version of circleci (2.0, 2.1, end so on)
version: 2.1

# definition of execution in job
commands:
    sayhello:
        description: "A very simple command for demonstration purposes"
        parameters:
            to:
                type: string
                default: "Hello World"
        steps:
            - run: echo << parameters.to >>

# job part
jobs:
    build:
        docker:
            - image: circleci/node:4.8.2
        steps:
            - checkout
            - run: echo "Hello World"
